<h2 style="font-family:timesnewroman; font-size:14pt; text-align:right">CB.ENP2AEL17002</h2>
<h2 style="font-family:timesnewroman; font-size:14pt; text-align:right">Anjali Mukherjee</h2>

<p style="font-family:timesnewroman; font-size:24pt; text-align:center; font-weight:bold">Control System Bootcamp Video 3</p>

In [1]:
from IPython.display import HTML
HTML("""
<iframe width="560" height="315" src="https://www.youtube.com/embed/h7nJ6ZL4Lf0" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
  
</iframe>
""")

<h1 style="font-family:timesnewroman">Stability and Eigen Values</h1>

<h2 style="font-family:timesnewroman">Recap: </h2>

<ul style="font-family:timesnewroman; font-size:14pt"><li>Equation of a system: <br><br><center> $ \dot X = AX , X \epsilon R^n $</center></li>
<li>Solution: <br><br><center> $X(t) = e^{At}X(0)$</center><br></li>
<li>Taylor series expansion of $e^At$: <br><br><center>$e^At = I + At+ \frac{A^2t^2}{2!}+\frac{A^3t^3}{3!}+...$</center><br></li>
<li>A in terms of its eigen values and eigen vectors: <br><br> <center> $ A= TDT^{-1}$</center><br></li>
<li>Writing X in terms of eigen vectors: <br><br> <center> $ X = Tz$</center><br><br> <center> $\dot X = T\dot z$</center> <br><br> <center> $ \dot z = Dz$</center><br></li>

<li>It is simple to see the system dynamics if the system equation is broken down into eigen values and eigen vectors.<br><br>
<center>$e^{At} = e^{TDT^{-1}} = TT^{-1}+TDT^{-1}+ (TDT^{-1}TDT^{-1})\frac{t^2}{2!}+... = Te^{Dt}T^{-1}$<br><br>$\begin{equation}X(t) = Te^{Dt}T^{-1}X(0)\end{equation}$ <br><br> $D = \begin{bmatrix}\lambda_1 & 0 & ...&0 \\0 &\lambda_2 & ... & 0 \\ \vdots & \vdots &\ddots &\vdots\\  0 & 0&... &\lambda_n  \end{bmatrix}$</center></li>
<li>Easy to compute $e^{Dt}$ and $T$ can be computed as shown in below code.</li>

In [4]:
import numpy as np
A = np.array([[1, 2, 3], [2, 1, 2], [3, 1, 3]])
d, T = np.linalg.eig(A)
D= np.diag(d) 
print("T = ",T,"\n\n","D = ",D)

T =  [[-0.56730355 -0.82570297 -0.28510867]
 [-0.47420984  0.26890404 -0.76169163]
 [-0.67326942  0.49588832  0.58184096]] 

 D =  [[ 6.23216886  0.          0.        ]
 [ 0.         -1.45302863  0.        ]
 [ 0.          0.          0.22085977]]


<h1 style="font-family:timesnewroman">Stability of Continuous Time Systems:</h1>

<p style="font-family:timesnewroman; font-size:14pt">What happens to the system when time goes to infinity? Does it tend to infinity or it goes down to zero or something different happens?

$e^{Dt}$ is responsible for all this. </p>

<p style="font-family:timesnewroman; font-size:14pt; text-align:center">$e^{Dt} = \begin{bmatrix}e^{\lambda_1} & 0 & ...&0 \\0 &e^{\lambda_2} & ... & 0 \\ \vdots & \vdots &\ddots &\vdots\\  0 & 0&... &e^{\lambda_n}  \end{bmatrix}$</p>

<p style="font-family:timesnewroman; font-size:14pt">Depending on the eigen values, even if one component of $e^{DT}$ becomes infinity, the equation $\begin{equation}X(t) = Te^{Dt}T^{-1}X(0)\end{equation}$ will tend to infinity as time tends to infinity.

\begin{equation} \lambda = a +\imath b \end{equation} ie., \begin{equation} e^{\lambda t} = e^{at}[{cos(bt) +\imath sin (bt)}] \end{equation}<br>

If $A, X$ all are real, $ \dot X = AX$ has real solutions.

${cos(bt) +\imath sin (bt)}$ has amplitude always less than or equal to 1. Thus $e^{at}$ decides the fate of the system as given below.</p>
<br><br><p style="font-family:timesnewroman; font-size:14pt"> When $a>0$, system blows up to infinity,
![When $a>0$](graph1.jpg)
<br> When $a<0$, system settles down to zero.
![When $a>0$](graph2.jpg)

i.e., All the eigen values should have negative real part for the system to be stable. Even if one of them is negative, that particular component will make the system unstable.

So, in short, If we represent this graphically on the complex plane $\lambda \in C$, 


![stability](graph3.jpg)

When the eigen values lie to the left side of the complex plane, system is stable. When they lie on the right side, system is unstable, and to make it stable we have to steer the eigen values towards left side by adding the control part into the equation (ie., equation of the system now becomes $\dot X = AX + BU$)<br>

The whole system thus can be characterized using just the eigen values.</p>




<h1 style="font-family:timesnewroman">Stability of Discrete Time Systems</h1>

<p style="font-family:timesnewroman; font-size:14pt">In a physical system, data is not recorded continuously. What we get is discrete data at fixed increments of interval of time $\Delta t$.

So, we define a discrete time system with the equation given below,</p>

<p style="font-family:timesnewroman; font-size:14pt; text-align:center">$\begin{equation} X_{k+1} = \tilde A  X_k\end{equation} $ where $X_k = X(k\Delta t)$</p>

<p style="font-family:timesnewroman; font-size:14pt">The system is measured at individual $\Delta t$ instances of time and the above equation gives an update about what state of the system would be in the next $k+1^{th}$ instant

\begin{equation} \tilde A = e^{A\Delta t}\end{equation}

$\tilde A$ and $A $ are related by the exponential relation.

Notion of stability is different for the discrete time systems. 

Assuming that the initial condition $X_0$ is known, we can define a whole set of measurements by just multiplying by $\tilde A$ as follows.</p>

<p style="font-family:timesnewroman; font-size:14pt;text-align:center"><br>$X_1 = \tilde A X_0$  <br> $X_2 = \tilde A X_1 = \tilde {A^2} X_0$ <br> $X_3 = \tilde {A^3} X_0$<br> $X_4 = \tilde {A^4} X_0$ <br> $\vdots$<br> $X_N = \tilde {A^N} X_0$</p>

<p style="font-family:timesnewroman; font-size:14pt">Like in the continuous time case, we can write $\tilde A$ in terms of its eigen values and eigen vectors as $\tilde T\tilde D\tilde T^{-1}$.

We can see that, the powers only affect the diagonal matrix D, and thus in each equation, $\lambda$, $\lambda^2$, $\lambda^3$,...,$\lambda^N$ appears. </p>

<p style="font-family:timesnewroman; font-size:14pt; text-align:center"><br> $ \lambda = Re^{i\theta} $ (Representing in polar form on complex plane)
![complex plane](graph4.jpg)
<br><br>$\lambda^N = R^N e^{iN\theta}$</p>

<p style="font-family:timesnewroman; font-size:14pt">So, it is the radius of the eigen value that grows or shrinks. If radius $R$ is greater than 1, as N increases, R goes to infinity and the system becomes unstable. If $R$ is less than 1, the system decays to zero as N increases and becomes stable. Representing this on the complex plane, 

![complex unit circle](graph5.jpg)

$\begin{equation} \tilde A = e^{A\Delta t}\end{equation}$ maps discrete time system to the continuous time case described above.

Summarizing, in continuous as well as discrete systems, the system stability depends only on the eigen values of the system. In continuous time, if all eigen values have negative real part, the system is stable. In discrete time system, the eigen value should lie within a unit circle, that is the magnitude should be less than One, for the system to be stable.</p>


